# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d0a68beaf0716e9ab1f7d3b39115f9956ef37b50225460b1e959ee9ba6f1eb2613645c141cd56b3b33b7c872d2e1a155c78a62208383c858b25c751b30fedfd

test:
  secret_key_base: e61d410e7b37db30b1565295cd640cb32e03eca2917b38bd41d30e9553b437a31c1e69f1823b9962819eaa294dcf01d25ae2bb7493e4925e76edc5afe2772fef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
